### ISSUE TITLE
Reasons for a new project?

### ISSUE THREAD

**Issue by bam80** [accumulator/plugin.video.lbry#1]
Hi, could you explain how your work correlates with the others?

>  I don't know why they decided to make their own version, I assume they have a reason they didn't want to use this one.

https://github.com/stellartux/plugin.video.lbry/issues/4

**Comment by accumulator** [comment]
There's no real correlation. I recently started checking out lbry, and did find and try stellartux's plugin, but it was very basic still and occasionally ran into errors making it not really usable for me. Also, the project on github looked abandoned, so I decided to start from scratch.

**Comment by bam80** [comment]
Thanks. Anyway, it seems live again. So maybe it worth to join the efforts:

> I'm happy to accept pull requests or suggestions from anyone.
