### ISSUE TITLE
Backported Leia branch for users that are not able to comfortably switch to Matrix

### ISSUE THREAD

**Issue by amacchietto** [accumulator/plugin.video.lbry#11]
The current main branch is only compatible with Kodi Matrix. I created a Leia branch and backported all functionality of the main Matrix branch. Kodi Matrix is still in Beta with LibreElec and some devices may not have the necessary stability to be  used comfortably (I encountered quite a few issues using an Rpi4).

The branch is located here:

https://github.com/amacchietto/plugin.video.lbry/tree/leia-18.9

Unfortunately, it doesn't seem possible to create a pull request if the branch doesn't exist on the target.

**Comment by accumulator** [comment]
Kodi Matrix is probably the worst release I've seen :)
My initial idea was to wait out the problem, assuming they would tackle all the regressions, but it seems that can take a while.

I'll create a leia branch and merge your backported patches

Please change the version number to 0.1.4 as that will be the next release

**Comment by amacchietto** [comment]
> Please change the version number to 0.1.5 as that will be the next release

Done.

**Comment by accumulator** [comment]
Thanks for backporting @amacchietto. I have added PRs to the repo for both matrix and leia versions, so hopefully they will be available generally soon!
