### ISSUE TITLE
Question: Fork of your code for Rumble possible?

### ISSUE THREAD

**Issue by Isayso** [accumulator/plugin.video.lbry#13]
I was wondering if your code base can be used to modify it for rumble. 
There is an addon available for Matrix, but Matrix on RPI3 is unusable. I used Matrix since Milhouse libreelec builds and downgraded back to Leia last week. 
The rumble Matrix addon is encrypted. 

I found some help pages for the rumble api  [https://player.rumble.com/developers/Rumble-Player-API.html](https://player.rumble.com/developers/Rumble-Player-API.html) or [https://www.rumbleplayer.com/developers/Rumble-Platform-API.html](https://www.rumbleplayer.com/developers/Rumble-Platform-API.html)

Can you take a look inside and tell me if your code can be modified for rumble? Thanks!

**Comment by accumulator** [comment]
Rumble looks more like a video platform, instead of a media center.
I don't think this code is in any way useful for rumble..
