### ISSUE TITLE
API error:   json: cannot unmarshal string ...

### ISSUE THREAD

**Issue by 99filllip** [accumulator/plugin.video.lbry#21]
hello,
when i try to use the addon i get the following error message:
json: cannot unmarshal string into Go struct field RPCrequest.id of type int

this happens on rpi3b+ with libreelec (kodi leila) and khadas vim3 with coreelec (kodi matrix)
any idea what to do?

thanks.

**Comment by Qedinux** [comment]
I'm also concerned about this issue.

I'm using Kodi 19.3 / Ubuntu 20.04.3 LTS / Kernel 5.4.0-99-generic / Intel NUC 5th Gen

Waiting for an update.
Thanks.

**Comment by Qedinux** [comment]
I downgraded to the previous version, 0.1.6+matrix.1
Using this version, the addon is working on my system.

**Comment by accumulator** [comment]
what action triggers this error?

**Comment by 99filllip** [comment]
> what action triggers this error?

any. wether search or followed channels, it always pops up. 
for now i downgraded too, and am ok with older versions on both devices (rpi3 and khadas vim3)

**Comment by accumulator** [comment]
quick fix: you can edit line ~44 and replace `'id': '1'` with `'id': 1` (unquote the 1)

**Comment by 99filllip** [comment]
> quick fix: you can edit line ~44 of `plugin.py` and replace `'id': '1'` with `'id': 1` (unquote the 1)

ok, ill try later. i'll report back...

**Comment by accumulator** [comment]
fixed version 0.2.1 submitted to kodi plugin repository.

Problem was missed, because it only triggers when using the https://api.lbry.tv/api/v1/proxy API server, not when using a local API server.

**Comment by accumulator** [comment]
thanks for reporting!

**Comment by Qedinux** [comment]
Today I updated this extension with the latest version 0.2.1.

It is now working fine.

 

Thank you to fix it quickly.
