### ISSUE TITLE
API Error 405

### ISSUE THREAD

**Issue by joelmaxuel** [accumulator/plugin.video.lbry#22]
"HTTP Error 405: Method Not Allowed" when trying to access latest videos (prior-set channels).

As also experienced by youtube-dl, as of November 17th.

https://github.com/ytdl-org/youtube-dl/issues/31362

There appears to be a workaround for video extraction in YTDL, but discovery and metadata necessary for this plugin is probably a whole other problem.

**Comment by amacchietto** [comment]
Changing the proxy url to https://api.na-backend.odysee.com/api/v1/proxy should fix the issue.

**Comment by joelmaxuel** [comment]
That did it. Thanks!

**Comment by accumulator** [comment]
Thx for the heads-up. I'll update the default.
