### ISSUE TITLE
How to get the API server working for LibreELEC on Raspbery Pi?

### ISSUE THREAD

**Issue by rtevans01** [accumulator/plugin.video.lbry#23]
Sorry but I'm lost. I want to be able to download videos and also contribute to the lbry network because I don't like leaching bandwidth all the time. My understanding from reading issues in this repo and elsewhere is I have to get lbrynet working by installing it on a PC connected to the same LAN. Is this correct? If so, I downloaded it to my Linux laptop, ran it in the terminal, changed the API server from https://api.na-backend.odysee.com/api/v1/proxy to http://localhost:5279 in the addon but whenever I click on "Followed Channel" it says API error. 

Does lbrynet have to be installed on the Raspberry Pi? If so, I transferred the zip to my LibreELEC samba share and extracted it but nothing happens when I click on it.  

Any help is appreciate. Thanks.

EDIT: I'm also trying to get help in a [different thread](https://github.com/lbryio/lbry-sdk/issues/3714). Might be more updated info there.

**Comment by accumulator** [comment]
If you want to run lbrynet on a different computer, you'll have to check that it is listening on all interfaces, e.g.

`lbrynet start --api 0.0.0.0:5279`

Then, you'll have to use the IP address of that computer in the URL of the API server, e.g.

`http://laptop.address:5279`
