### ISSUE TITLE
Kodi Matrix

### ISSUE THREAD

**Issue by okkebal** [accumulator/plugin.video.lbry#5]
Already posted this on https://github.com/stellartux/plugin.video.lbry/issues/6

LBRY plugin does not work in Kodi Matrix. If I manually up the python version in addon.xml to 3.0.0 it seems to work unil I go into one of my subcribed channels.

I cannot reproduce anything since i downgraded back to Leia. Sorry. Just wanted to let you know.

Just install Matrix and try the plugin to reproduce the error.

**Comment by accumulator** [comment]
Thanks for reminding me. I was postponing upgrading to Matrix release candidates but now that it's released it should be made available.

I fixed the compatiblity errors and the plugin update has been sent to the Kodi plugin repo maintainers.

**Comment by accumulator** [comment]
It has just been merged to the Kodi repo
